# Generated by Django 2.2.6 on 2019-10-27 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=200)),
                ('TEXT', models.TextField()),
                ('CREATED_ON', models.DateTimeField(default=django.utils.timezone.now)),
                ('PUBLISHED_ON', models.DateTimeField(blank=True, null=True)),
                ('AUTHOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
